@startwbs
* Windows 10 VDI
** Open VSC create new folder for your env build
*** git clone https://github.optum.com/IAC-COE/vdiOrchestration.git to new folder in VSC
** Day1 Initial Build Instructions
*** Run ./Day0_InitialSetup.ps1 -Day1
*** Run ./Day1_FileMods.ps1 -MakeFiles
*** Run ./Day1_FileMods.ps1 -ModTF
*** Modify terraform.tfvars (script opens automatically for editing in VSC)
*** Modify *.tf files name/valuevaule pairs if needed: CPU, Memory, Disks, Servertype, vRA Description
*** Run ./Day1_FileMods.ps1 -ModS3
*** Run ./Day1_Orchestration.ps1 -RunTF
*** Inspec steps can be run once TF builds are complete
*** Run ./Day1_Orchestration.ps1 -inspec
*** Run ./Day1_RunInspecTests.ps1 -inspec
@endwbs