@startwbs
* Day2 Work Instructions
** Day2 Options
*** CPU Changes
*** Memory Changes
*** Change Owner
*** VRA Shared Acces Group
*** Filesystem Setup for New Disk
** Day2 TF File Modifications
*** Edit all tf files, changing values needed
*** Run ./Day1_Orchestration.ps1 -RunTF
** Day2 Filesystem Setup
*** Run ./Day0_InitialSetup.ps1 -day2
**** Linux Server Setup
***** Edit Day2Work\Day2_Filesystems\RHEL\cookbooks\optum_filesystem_wrapper\attributes\redhat.rb with correct values
***** Navigate to folder Day2Work\Day2_Filesystems\RHEL, its above the cookbooks folder
***** Run: pscp -r cookbooks 2NDUNIXID@SERVERNAME.uhc.com:/home/2NDUNIXID
***** Run: ssh 2NDUNIXID@SERVERNAME.uhc.com sudo chef-client -zo optum_filesystem_wrapper
**** Windows Server Setup
***** Navigate to folder Day2Work\Day2_Filesystems\Windows
***** Edit Windows_UAT.ps1 file
***** For each server copy rows 3-7 (1st invoke - pause)
***** Then edit the FQDN with the Server name. there should be 4 replacments for each server
***** Save File, then run ./Windows_UAT.ps1
** Day2 Inspec Runs
*** These are manual at this time and are defined by your app team on what to run
*** Folder structure is setup (Day2_inspec) for files to be placed and run manually
@endwbs