@startwbs
* Windows 10 VDI
** Open VSC create new folder for your env build
*** git clone https://github.optum.com/IAC-COE/vdiOrchestration.git to new folder in VSC
** Developer Provider Instructions
*** Run ./Day0_InitialSetup.ps1 -Day1
*** Run ./Day1_FileMods.ps1 -UAT
*** terraform.tfvars automatically configured for run (no need to edit)
*** Run ./Day1_Orchestration.ps1 -RunTF
*** Inspec steps below can be run once TF builds are complete
*** Run ./Day1_Orchestration.ps1 -inspec
*** Run ./Day1_RunInspecTests.ps1 -inspec
@endwbs