@startuml

' Just shows getting on to VDI and cloning the repo
' actor EndUser
' EndUser -> VDI: Logon
' VDI -> TFproviderUAT_Repo: git clone

actor EndUserVDI
participant InitialSetup order 10
participant RunInitialServerBuilds order 20
participant RunInspecControls order 30
participant RunInspecTests order 40
participant BaseStructure order 100
participant Servers order 110

' enduser -> InitialSetup: vsc window
' Step 1 of process
    InitialSetup -> BaseStructure:-now 
    hnote right : Creates Day 1 base folders/files 
    InitialSetup -> BaseStructure:-day2
    hnote right : Creates Day 2 base folders/files
    InitialSetup -> BaseStructure:-ResetTF
    hnote right : Removes .terraform folder
    InitialSetup -> BaseStructure:-ResetAll
    hnote right : Removes all folder/files
    InitialSetup -> BaseStructure:-ValidateIac
    hnote right : Validates all IAC software is configured

' enduser -> RunInitialServerBuilds: vsc window
' Step 2 of process
    RunInitialServerBuilds -> BaseStructure:-ModTF 
    hnote right #aqua : Modifies the TF build files 
    RunInitialServerBuilds -> BaseStructure:-now
    hnote right #aqua : Run TF and builds devices in vRa 

' Step 3 of process
    RunInspecControls -> BaseStructure: 
    hnote right #ffaaaa 
        Creates server specific Inspec controls
        based on terraform statefile, "servername.rb"
    end note

' Step 4 of process
    RunInspecTests -> Servers: inspec exec 
    hnote right #lightgreen 
        Runs Inspec tests directly against servers
        based on server type
    end note
@enduml